"""
This script processes the data generated by `3dsw_generation.py`.
It iterates through the `multiple_cases` directory, loads the HDF5 snapshots for each case,
extracts 'height' and 'vorticity' fields, downsamples them, and consolidates all cases
into a single .mat file for further analysis or training.
"""
import numpy as np
import h5py
import os
from scipy.io import savemat

def load_and_process_case(case_dir):
    """Load and process data from a single case directory."""
    snapshot_files = sorted([f for f in os.listdir(os.path.join(case_dir, 'snapshots')) 
                           if f.endswith('.h5')])
    
    # Initialize lists to store data
    height_data = []
    vorticity_data = []
    
    # Load data from each snapshot
    for snapshot_file in snapshot_files:
        with h5py.File(os.path.join(case_dir, 'snapshots', snapshot_file), 'r') as f:
            # Load height and vorticity data
            height = f['tasks']['height']  # Get the last write
            vorticity = f['tasks']['vorticity']  # Get the last write
            
            # Downsample by factor of 8
            height_downsampled = height[:, ::4, ::4]
            vorticity_downsampled = vorticity[:, ::4, ::4]
            
            height_data.append(height_downsampled)
            vorticity_data.append(vorticity_downsampled)
    
    return np.array(height_data), np.array(vorticity_data)

def main():
    base_dir = 'multiple_cases'
    
    # Get all case directories
    case_dirs = sorted([d for d in os.listdir(base_dir) 
                       if os.path.isdir(os.path.join(base_dir, d))])
    
    all_data = []
    
    # Process each case
    for case_dir in case_dirs:
        print(f"Processing {case_dir}...")
        height_data, vorticity_data = load_and_process_case(os.path.join(base_dir, case_dir))
        
        # Combine height and vorticity along a new axis
        # Shape will be (time_steps, 2, downsampled_height, downsampled_width)
        combined_data = np.stack([height_data, vorticity_data], axis=2)
        all_data.append(combined_data)
    
    # Stack all cases
    # Final shape: (n_cases, time_steps, 2, height/8, width/8)
    all_data = np.concatenate(all_data, axis=0)
    
    # Save to .mat file
    print("Saving data to .mat file...")
    savemat(f'3dShallowWater_{all_data.shape[0]}x{all_data.shape[1]}x{all_data.shape[2]}x{all_data.shape[3]}x{all_data.shape[4]}.mat', {
        'data': all_data,
        'data_description': '''
        Shape: (n_cases, time_steps, 2, height/8, width/8)
        Axis meanings:
        - axis 0: different cases (different hpert values)
        - axis 1: time steps
        - axis 2: physical quantities (0: height, 1: vorticity)
        - axis 3: latitude (downsampled by 8)
        - axis 4: longitude (downsampled by 8)
        '''
    })
    print("Done!")

if __name__ == '__main__':
    main()
